apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: serve
  name: serve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serve
  template:
    metadata:
      labels:
        app: serve
    spec:
      containers:
      - image: bitnami/wildfly:26
        name: wildfly
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: WILDFLY_USERNAME
          value: root
        - name: WILDFLY_PASSWORD
          value: 123
        - name: WILDFLY_MANAGEMENT_LISTEN_ADDRESS
          value: 0.0.0.0
        ports:
        - containerPort: 9990
          name: wildfly
        

