apiVersion: v1
kind: Service
metadata:
  labels:
    app: wildfly
  name: wildfly
spec:
  type: NodePort
  ports:
    - name: "wildfly-service"   
      port: 9990     
      targetPort: 80
      NodePort: 31001
  selector:
    app: wildfly

